# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  #- name: Home
  #  url: '#about'
  #  weight: 10
  - name: About me
    url: '#experience'
    weight: 10 
  - name: Teaching Activities
    identifier: teaching
    weight: 20
  - name: Courses
    url: 'courses'
    parent: teaching
    weight: 10
  - name: Thesis Supervision
    url: 'supervision'
    parent: teaching
    weight: 20
  - name: Student Projects
    url: 'student_project'
    parent: teaching
    weight: 30
  #- name: Further Education
  #  url: 'weiterbildung'
  #  parent: teaching
  #  weight: 30
  - name: Publications
    identifier: publications
    weight: 30
  - name: Published Work
    url: 'publication'
    parent: publications
    weight: 10
  - name: Datasets
    url: 'dataset'
    parent: publications
    weight: 20
  - name: Research Activities
    identifier: research
    weigth: 10
  - name: Projects
    url: '#projects'
    parent: research
    weigth: 20
  - name: Talks & Outreach
    url: 'event'
    weight: 50
  - name: News
    url: '#news'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
